// Include
#include "level.h"

#include "utils/functions.h"
#include "utils/log.h"

#include <yaml-cpp/yaml.h>
#include <filesystem>
// TODO: for all yaml formats, use attributes aswell. (current data is autogenerated)

// Game
namespace Game {
	const std::string levelDataPath = "data/level/";

	const auto read_list = [](const YAML::Node& node, std::string_view nodeName, auto& list) {
		if (node[nodeName.data()] && node[nodeName.data()].IsSequence()) {
			for (const auto& child : node[nodeName.data()]) {
				decltype(auto) data = list.emplace_back();
				data.Read(child);
			}
		}
	};

	const auto read_vec3 = [](const YAML::Node& node) {
		glm::vec3 data;
		data.x = node["x"].as<float>(0.0f);
		data.y = node["y"].as<float>(0.0f);
		data.z = node["z"].as<float>(0.0f);
		return data;
	};

	// TriggerVolumeEvents
	void TriggerVolumeEvents::Read(const YAML::Node& node) {
		mOnEnter = node["onEnterEvent"].as<std::string>("");
		mOnExit = node["onExitEvent"].as<std::string>("");
	}

	// TriggerVolumeData
	void TriggerVolumeData::Read(const YAML::Node& node) {
		mShape = static_cast<TriggerVolumeShape>(node["shape"].as<uint32_t>(0));
		mActivationType = static_cast<TriggerVolumeActivationType>(node["triggerActivationType"].as<uint32_t>(0));

		if (node["offset"]) {
			mOffset = read_vec3(node["offset"]);
		}

		mOnEnter = node["onEnter"].as<std::string>("");
		mOnExit = node["onExit"].as<std::string>("");
		mOnStay = node["onStay"].as<std::string>("");
		mLuaCallbackOnEnter = node["luaCallbackOnEnter"].as<std::string>("");
		mLuaCallbackOnExit = node["luaCallbackOnExit"].as<std::string>("");
		mLuaCallbackOnStay = node["luaCallbackOnStay"].as<std::string>("");

		mTimeToActivate = node["timeToActivate"].as<float>(0.0f);

		mUseObjectDimensions = node["useGameObjectDimensions"].as<bool>(false);
		mIsKinematic = node["isKinematic"].as<bool>(false);
		mPersistentTimer = node["persistentTimer"].as<bool>(false);
		mTriggerOnceOnly = node["triggerOnceOnly"].as<bool>(false);
		mTriggerIfNotBeaten = node["triggerIfNotBeaten"].as<bool>(false);

		switch (mShape) {
			case TriggerVolumeShape::Sphere:
				mBoundingBox.extent = glm::vec3(node["sphereRadius"].as<float>(1.0f));
				break;

			case TriggerVolumeShape::Box:
				mBoundingBox.extent = glm::vec3(
					node["boxWidth"].as<float>(1.0f),
					node["boxHeight"].as<float>(1.0f),
					node["boxLength"].as<float>(1.0f)
				);
				break;

			case TriggerVolumeShape::Capsule:
				auto radius = node["capsuleRadius"].as<float>(1.0f);
				mBoundingBox.extent = glm::vec3(radius, node["capsuleHeight"].as<float>(1.0f), radius);
				break;
		}

		if (node["events"]) {
			mEvents.Read(node["events"]);
		}
	}

	const BoundingBox& TriggerVolumeData::GetBoundingBox() const {
		return mBoundingBox;
	}

	const glm::vec3& TriggerVolumeData::GetOffset() const {
		return mOffset;
	}

	TriggerVolumeShape TriggerVolumeData::GetShape() const {
		return mShape;
	}

	TriggerVolumeActivationType TriggerVolumeData::GetActivationType() const {
		return mActivationType;
	}

	float TriggerVolumeData::GetTimeToActivate() const {
		return mTimeToActivate;
	}

	// TeleporterData
	void TeleporterData::Read(const YAML::Node& node) {
		mDestinationMarkerId = node["destinationMarkerId"].as<uint32_t>(0);
		mDeferTriggerCreation = node["deferTriggerCreation"].as<bool>(false);

		if (node["triggerVolume"]) {
			mTriggerVolumeData = std::make_unique<TriggerVolumeData>();
			mTriggerVolumeData->Read(node["triggerVolume"]);
		}
	}

	const std::unique_ptr<TriggerVolumeData>& TeleporterData::GetTriggerVolumeData() const {
		return mTriggerVolumeData;
	}

	uint32_t TeleporterData::GetDestinationId() const {
		return mDestinationMarkerId;
	}

	bool TeleporterData::DeferTriggerCreation() const {
		return mDeferTriggerCreation;
	}

	// MarkerInteractableData
	void MarkerInteractableData::Read(const YAML::Node& node) {
		mAbility = node["interactableAbility"].as<std::string>("");
		mStartInteractEvent = node["startInteractEvent"].as<std::string>("");
		mEndInteractEvent = node["endInteractEvent"].as<std::string>("");
		mOptionalInteractEvent = node["optionalInteractEvent"].as<std::string>("");

		mUsesAllowed = node["numUsesAllowed"].as<int32_t>(0);
		mChallengeValue = node["challengeValue"].as<int32_t>(0);
	}

	const std::string& MarkerInteractableData::GetAbility() const {
		return mAbility;
	}

	const std::string& MarkerInteractableData::GetStartInteractEvent() const {
		return mStartInteractEvent;
	}

	const std::string& MarkerInteractableData::GetEndInteractEvent() const {
		return mEndInteractEvent;
	}

	const std::string& MarkerInteractableData::GetOptionalInteractEvent() const {
		return mOptionalInteractEvent;
	}

	int32_t MarkerInteractableData::GetUsesAllowed() const {
		return mUsesAllowed;
	}

	int32_t MarkerInteractableData::GetChallengeValue() const {
		return mChallengeValue;
	}

	// Marker
	void Marker::Read(const YAML::Node& node) {
		mName = node["markerName"].as<std::string>("");
		mId = node["markerId"].as<uint32_t>(0);
		mNounName = node["nounDef"].as<std::string>("");
		mNoun = utils::hash_id(mNounName);

		if (node["pos"]) {
			mPosition = read_vec3(node["pos"]);
		}
		if (node["rotDegrees"]) {
			mRotation = read_vec3(node["rotDegrees"]);
		}
		mScale = node["scale"].as<float>(1.0f);

		mVisible = node["visible"].as<bool>(false);
		mHasCollision = node["createWithCollision"].as<bool>(false);

		mOverrideAssetId = node["assetOverrideId"].as<uint64_t>(0);
		mTargetId = node["targetMarkerId"].as<uint32_t>(0);

		if (node["componentData"]) {
			if (node["componentData"]["teleporter"]) {
				mTeleporterData = std::make_unique<TeleporterData>();
				mTeleporterData->Read(node["componentData"]["teleporter"]);
			}

			if (node["componentData"]["interactable"]) {
				mInteractableData = std::make_unique<MarkerInteractableData>();
				mInteractableData->Read(node["componentData"]["interactable"]);
			}
			/*
			SharedComponentData->add("eventListenerDef", nullable_type, std::tuple(0x08, EventListenerDef));
			SharedComponentData->add("spawnPointDef", nullable_type, std::tuple(0x10, SpawnPointDef));
			SharedComponentData->add("spawnTrigger", nullable_type, std::tuple(0x0C, SpawnTriggerDef));
			SharedComponentData->add("defaultGfxState", nullable_type, std::tuple(0x18, GameObjectGfxStateTuning));
			SharedComponentData->add("combatant", nullable_type, std::tuple(0x1C, CombatantDef));
			SharedComponentData->add("triggerComponent", nullable_type, std::tuple(0x20, TriggerVolumeComponentDef));
			SharedComponentData->add("spaceshipSpawnPoint", nullable_type, std::tuple(0x24, SpaceshipSpawnPointDef));
			*/
		}
	}

	const std::unique_ptr<TeleporterData>& Marker::GetTeleporterData() const {
		return mTeleporterData;
	}

	const std::unique_ptr<MarkerInteractableData>& Marker::GetInteractableData() const {
		return mInteractableData;
	}

	const glm::vec3& Marker::GetPosition() const {
		return mPosition;
	}

	const glm::vec3& Marker::GetRotation() const {
		return mRotation;
	}

	const std::string& Marker::GetNounName() const {
		return mNounName;
	}

	uint64_t Marker::GetOverrideAssetId() const {
		return mOverrideAssetId;
	}

	uint32_t Marker::GetId() const {
		return mId;
	}

	uint32_t Marker::GetNoun() const {
		return mNoun;
	}

	uint32_t Marker::GetTargetId() const {
		return mTargetId;
	}

	float Marker::GetScale() const {
		return mScale;
	}

	// Markerset
	bool Markerset::Load(const std::string& path) {
		const std::string fullPath = levelDataPath + path;
		if (!std::filesystem::exists(fullPath)) {
			std::cout << "Markerset: Could not find '" << fullPath << "'." << std::endl;
			return false;
		}

		try {
			YAML::Node document = YAML::LoadFile(fullPath);
			if (document["markerset"]) {
				Read(document["markerset"]);
				return true;
			}
		} catch (const YAML::Exception& e) {
			std::cout << "Markerset: Could not load '" << path << "': " << e.what() << std::endl;
		}
		return false;
	}

	void Markerset::Read(const YAML::Node& node) {
		if (node["markers"] && node["markers"].IsSequence()) {
			for (const auto& child : node["markers"]) {
				auto marker = std::make_shared<Marker>();
				marker->Read(child);

				mMarkersByNoun[marker->mNoun].push_back(marker);
				mMarkers.push_back(std::move(marker));
			}
		}
	}

	const std::vector<MarkerPtr>& Markerset::GetMarkers() const {
		return mMarkers;
	}

	std::vector<MarkerPtr> Markerset::GetMarkersByType(uint32_t noun) const {
		if (auto it = mMarkersByNoun.find(noun); it != mMarkersByNoun.end()) {
			return it->second;
		}
		return {};
	}

	// DirectorClass
	void DirectorClass::Read(const YAML::Node& node) {
		mNounName = node["mpNoun"].as<std::string>("");

		mMinLevel = node["minDifficulty"].as<int32_t>(0);
		mMaxLevel = node["maxDifficulty"].as<int32_t>(100);

		mHordeLegal = node["hordeLegal"].as<bool>(true);
	}

	const std::string& DirectorClass::GetNounName() const {
		return mNounName;
	}

	int32_t DirectorClass::GetMinLevel() const {
		return mMinLevel;
	}

	int32_t DirectorClass::GetMaxLevel() const {
		return mMaxLevel;
	}

	bool DirectorClass::IsHordeLegal() const {
		return mHordeLegal;
	}

	// LevelConfig
	void LevelConfig::Read(const YAML::Node& node) {
		read_list(node, "minion", mMinions);
		read_list(node, "special", mSpecial);
		read_list(node, "boss", mBoss);
		read_list(node, "agent", mAgent);
		read_list(node, "captain", mCaptain);
	}

	DirectorClass LevelConfig::GetMinion(size_t idx) const {
		return mMinions.size() > idx ? mMinions[idx] : DirectorClass();
	}

	DirectorClass LevelConfig::GetSpecial(size_t idx) const {
		return mSpecial.size() > idx ? mSpecial[idx] : DirectorClass();
	}

	DirectorClass LevelConfig::GetBoss(size_t idx) const {
		return mBoss.size() > idx ? mBoss[idx] : DirectorClass();
	}

	DirectorClass LevelConfig::GetAgent(size_t idx) const {
		return mAgent.size() > idx ? mAgent[idx] : DirectorClass();
	}

	DirectorClass LevelConfig::GetCaptain(size_t idx) const {
		return mCaptain.size() > idx ? mCaptain[idx] : DirectorClass();
	}

	// Level
	Level::Level() {

	}

	Level::~Level() {

	}

	bool Level::Load(const std::string& difficultyName, const std::string& levelName) {
		const std::string fullPath = levelDataPath + difficultyName + "/" + levelName + ".level.yaml";
		if (!std::filesystem::exists(fullPath)) {
			std::cout << "Level: Could not find '" << fullPath << "'." << std::endl;
			return false;
		}

		try {
			YAML::Node document = YAML::LoadFile(fullPath);
			if (!document["level"]) {
				return false;
			}

			const auto& node = document["level"];

			if (node["markersets"] && node["markersets"].IsSequence()) {
				for (const auto& child : node["markersets"]) {
					const auto markersetAsset = child["markersetAsset"].as<std::string>("");
					if (markersetAsset.empty()) {
						continue;
					}

					const auto& [it, added] = mMarkersets.try_emplace(utils::hash_id(markersetAsset));
					if (added) {
						it->second.mName = markersetAsset;
						it->second.Load(difficultyName + "/" + markersetAsset + ".yaml");
					}
				}
			}

			if (node["levelConfig"]) {
				mConfig.Read(node["levelConfig"]);
			}
			if (node["firstTimeConfig"]) {
				mFirstTimeConfig.Read(node["firstTimeConfig"]);
			}

			const auto planetConfigName = node["planetConfig"].as<std::string>("");
			if (!planetConfigName.empty()) {
				// mPlanetConfig.Read(open_the_file);
			}

			return true;
		} catch (const YAML::Exception& e) {
			std::cout << "Level: Could not load '" << fullPath << "': " << e.what() << std::endl;
		}
		return false;
	}

	bool Level::GetMarkerset(const std::string& name, Markerset& markerset) const {
		if (auto it = mMarkersets.find(utils::hash_id(name)); it != mMarkersets.end()) {
			markerset = it->second;
			return true;
		}
		return false;
	}

	const LevelConfig& Level::GetConfig() const {
		return mConfig;
	}

	const LevelConfig& Level::GetFirstTimeConfig() const {
		return mFirstTimeConfig;
	}

	const LevelConfig& Level::GetPlanetConfig() const {
		return mPlanetConfig;
	}
}