// Include
#include "level.h"

#include "utils/functions.h"
#include "utils/log.h"

#include <filesystem>
#include <iostream> // For debug logging

// TODO: for all xml formats, use attributes as well. (current data is autogenerated)

// Game
namespace Game {

    const std::string levelDataPath = "data/level/";

    // Lambda: read_list
    const auto read_list = [](pugi::xml_node node, std::string_view nodeName, auto& list) {
        std::cout << "[DEBUG] Reading list for nodeName: " << nodeName << std::endl;
        for (const auto& child : node.child(nodeName.data())) {
            if (!utils::string_iequals(child.name(), "entry")) {
                continue;
            }

            std::cout << "[DEBUG] Processing an entry in list '" << nodeName << "'." << std::endl;
            decltype(auto) data = list.emplace_back();
            data.Read(child);
        }
        std::cout << "[DEBUG] Finished reading list for nodeName: " << nodeName << std::endl;
    };

    // Lambda: read_vec3
    const auto read_vec3 = [](pugi::xml_node node) {
        std::cout << "[DEBUG] Reading vec3 from node: " << node.name() << std::endl;
        glm::vec3 data;
        data.x = utils::xml_get_text_node<float>(node, "x");
        data.y = utils::xml_get_text_node<float>(node, "y");
        data.z = utils::xml_get_text_node<float>(node, "z");
        std::cout << "[DEBUG] Read vec3: (" << data.x << ", " << data.y << ", " << data.z << ")" << std::endl;
        return data;
    };

    // TriggerVolumeEvents
    void TriggerVolumeEvents::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] TriggerVolumeEvents::Read started." << std::endl;
        mOnEnter = utils::xml_get_text_node(node, "onEnterEvent");
        std::cout << "[DEBUG] onEnterEvent: " << mOnEnter << std::endl;
        mOnExit = utils::xml_get_text_node(node, "onExitEvent");
        std::cout << "[DEBUG] onExitEvent: " << mOnExit << std::endl;
        std::cout << "[DEBUG] TriggerVolumeEvents::Read finished." << std::endl;
    }

    // TriggerVolumeData
    void TriggerVolumeData::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] TriggerVolumeData::Read started." << std::endl;
        mShape = utils::xml_get_text_node<TriggerVolumeShape>(node, "shape");
        std::cout << "[DEBUG] shape: " << static_cast<int>(mShape) << std::endl;
        mActivationType = utils::xml_get_text_node<TriggerVolumeActivationType>(node, "triggerActivationType");
        std::cout << "[DEBUG] triggerActivationType: " << static_cast<int>(mActivationType) << std::endl;

        mOffset = read_vec3(node.child("offset"));

        mOnEnter = utils::xml_get_text_node(node, "onEnter");
        std::cout << "[DEBUG] onEnter: " << mOnEnter << std::endl;
        mOnExit = utils::xml_get_text_node(node, "onExit");
        std::cout << "[DEBUG] onExit: " << mOnExit << std::endl;
        mOnStay = utils::xml_get_text_node(node, "onStay");
        std::cout << "[DEBUG] onStay: " << mOnStay << std::endl;
        mLuaCallbackOnEnter = utils::xml_get_text_node(node, "luaCallbackOnEnter");
        std::cout << "[DEBUG] luaCallbackOnEnter: " << mLuaCallbackOnEnter << std::endl;
        mLuaCallbackOnExit = utils::xml_get_text_node(node, "luaCallbackOnExit");
        std::cout << "[DEBUG] luaCallbackOnExit: " << mLuaCallbackOnExit << std::endl;
        mLuaCallbackOnStay = utils::xml_get_text_node(node, "luaCallbackOnStay");
        std::cout << "[DEBUG] luaCallbackOnStay: " << mLuaCallbackOnStay << std::endl;

        mTimeToActivate = utils::xml_get_text_node<float>(node, "timeToActivate");
        std::cout << "[DEBUG] timeToActivate: " << mTimeToActivate << std::endl;

        mUseObjectDimensions = utils::xml_get_text_node<bool>(node, "useGameObjectDimensions");
        std::cout << "[DEBUG] useGameObjectDimensions: " << (mUseObjectDimensions ? "true" : "false") << std::endl;
        mIsKinematic = utils::xml_get_text_node<bool>(node, "isKinematic");
        std::cout << "[DEBUG] isKinematic: " << (mIsKinematic ? "true" : "false") << std::endl;
        mPersistentTimer = utils::xml_get_text_node<bool>(node, "persistentTimer");
        std::cout << "[DEBUG] persistentTimer: " << (mPersistentTimer ? "true" : "false") << std::endl;
        mTriggerOnceOnly = utils::xml_get_text_node<bool>(node, "triggerOnceOnly");
        std::cout << "[DEBUG] triggerOnceOnly: " << (mTriggerOnceOnly ? "true" : "false") << std::endl;
        mTriggerIfNotBeaten = utils::xml_get_text_node<bool>(node, "triggerIfNotBeaten");
        std::cout << "[DEBUG] triggerIfNotBeaten: " << (mTriggerIfNotBeaten ? "true" : "false") << std::endl;

        switch (mShape) {
            case TriggerVolumeShape::Sphere: {
                auto radius = utils::xml_get_text_node<float>(node, "sphereRadius");
                std::cout << "[DEBUG] Sphere shape detected, sphereRadius: " << radius << std::endl;
                mBoundingBox.extent = glm::vec3(radius);
                break;
            }
            case TriggerVolumeShape::Box: {
                float width = utils::xml_get_text_node<float>(node, "boxWidth");
                float height = utils::xml_get_text_node<float>(node, "boxHeight");
                float length = utils::xml_get_text_node<float>(node, "boxLength");
                std::cout << "[DEBUG] Box shape detected, width: " << width << ", height: " << height << ", length: " << length << std::endl;
                mBoundingBox.extent = glm::vec3(width, height, length);
                break;
            }
            case TriggerVolumeShape::Capsule: {
                float radius = utils::xml_get_text_node<float>(node, "capsuleRadius");
                float height = utils::xml_get_text_node<float>(node, "capsuleHeight");
                std::cout << "[DEBUG] Capsule shape detected, capsuleRadius: " << radius << ", capsuleHeight: " << height << std::endl;
                mBoundingBox.extent = glm::vec3(radius, height, radius);
                break;
            }
        }

        if (auto eventsNode = node.child("events")) {
            std::cout << "[DEBUG] Found 'events' node. Reading TriggerVolumeEvents." << std::endl;
            mEvents.Read(eventsNode);
        } else {
            std::cout << "[DEBUG] No 'events' node found in TriggerVolumeData." << std::endl;
        }
        std::cout << "[DEBUG] TriggerVolumeData::Read finished." << std::endl;
    }

    const BoundingBox& TriggerVolumeData::GetBoundingBox() const {
        std::cout << "[DEBUG] Getting TriggerVolumeData BoundingBox." << std::endl;
        return mBoundingBox;
    }

    const glm::vec3& TriggerVolumeData::GetOffset() const {
        std::cout << "[DEBUG] Getting TriggerVolumeData Offset: (" 
                  << mOffset.x << ", " << mOffset.y << ", " << mOffset.z << ")" << std::endl;
        return mOffset;
    }

    TriggerVolumeShape TriggerVolumeData::GetShape() const {
        std::cout << "[DEBUG] Getting TriggerVolumeData Shape: " << static_cast<int>(mShape) << std::endl;
        return mShape;
    }

    TriggerVolumeActivationType TriggerVolumeData::GetActivationType() const {
        std::cout << "[DEBUG] Getting TriggerVolumeData ActivationType: " << static_cast<int>(mActivationType) << std::endl;
        return mActivationType;
    }

    float TriggerVolumeData::GetTimeToActivate() const {
        std::cout << "[DEBUG] Getting TriggerVolumeData TimeToActivate: " << mTimeToActivate << std::endl;
        return mTimeToActivate;
    }

    // TeleporterData
    void TeleporterData::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] TeleporterData::Read started." << std::endl;
        mDestinationMarkerId = utils::xml_get_text_node<uint32_t>(node, "destinationMarkerId");
        std::cout << "[DEBUG] destinationMarkerId: " << mDestinationMarkerId << std::endl;
        mDeferTriggerCreation = utils::xml_get_text_node<bool>(node, "deferTriggerCreation");
        std::cout << "[DEBUG] deferTriggerCreation: " << (mDeferTriggerCreation ? "true" : "false") << std::endl;

        if (auto triggerVolumeNode = node.child("triggerVolume")) {
            std::cout << "[DEBUG] Found triggerVolume node in TeleporterData." << std::endl;
            mTriggerVolumeData = std::make_unique<TriggerVolumeData>();
            mTriggerVolumeData->Read(triggerVolumeNode);
        } else {
            std::cout << "[DEBUG] No triggerVolume node found in TeleporterData." << std::endl;
        }
        std::cout << "[DEBUG] TeleporterData::Read finished." << std::endl;
    }

    const std::unique_ptr<TriggerVolumeData>& TeleporterData::GetTriggerVolumeData() const {
        std::cout << "[DEBUG] Getting TeleporterData TriggerVolumeData." << std::endl;
        return mTriggerVolumeData;
    }

    uint32_t TeleporterData::GetDestinationId() const {
        std::cout << "[DEBUG] Getting TeleporterData DestinationId: " << mDestinationMarkerId << std::endl;
        return mDestinationMarkerId;
    }

    bool TeleporterData::DeferTriggerCreation() const {
        std::cout << "[DEBUG] Getting TeleporterData DeferTriggerCreation: " << (mDeferTriggerCreation ? "true" : "false") << std::endl;
        return mDeferTriggerCreation;
    }

    // MarkerInteractableData
    void MarkerInteractableData::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] MarkerInteractableData::Read started." << std::endl;
        mAbility = utils::xml_get_text_node(node, "interactableAbility");
        std::cout << "[DEBUG] interactableAbility: " << mAbility << std::endl;
        mStartInteractEvent = utils::xml_get_text_node(node, "startInteractEvent");
        std::cout << "[DEBUG] startInteractEvent: " << mStartInteractEvent << std::endl;
        mEndInteractEvent = utils::xml_get_text_node(node, "endInteractEvent");
        std::cout << "[DEBUG] endInteractEvent: " << mEndInteractEvent << std::endl;
        mOptionalInteractEvent = utils::xml_get_text_node(node, "optionalInteractEvent");
        std::cout << "[DEBUG] optionalInteractEvent: " << mOptionalInteractEvent << std::endl;

        mUsesAllowed = utils::xml_get_text_node<int32_t>(node, "numUsesAllowed");
        std::cout << "[DEBUG] numUsesAllowed: " << mUsesAllowed << std::endl;
        mChallengeValue = utils::xml_get_text_node<int32_t>(node, "challengeValue");
        std::cout << "[DEBUG] challengeValue: " << mChallengeValue << std::endl;
        std::cout << "[DEBUG] MarkerInteractableData::Read finished." << std::endl;
    }

    const std::string& MarkerInteractableData::GetAbility() const {
        std::cout << "[DEBUG] Getting MarkerInteractableData Ability: " << mAbility << std::endl;
        return mAbility;
    }

    const std::string& MarkerInteractableData::GetStartInteractEvent() const {
        std::cout << "[DEBUG] Getting MarkerInteractableData StartInteractEvent: " << mStartInteractEvent << std::endl;
        return mStartInteractEvent;
    }

    const std::string& MarkerInteractableData::GetEndInteractEvent() const {
        std::cout << "[DEBUG] Getting MarkerInteractableData EndInteractEvent: " << mEndInteractEvent << std::endl;
        return mEndInteractEvent;
    }

    const std::string& MarkerInteractableData::GetOptionalInteractEvent() const {
        std::cout << "[DEBUG] Getting MarkerInteractableData OptionalInteractEvent: " << mOptionalInteractEvent << std::endl;
        return mOptionalInteractEvent;
    }

    int32_t MarkerInteractableData::GetUsesAllowed() const {
        std::cout << "[DEBUG] Getting MarkerInteractableData UsesAllowed: " << mUsesAllowed << std::endl;
        return mUsesAllowed;
    }

    int32_t MarkerInteractableData::GetChallengeValue() const {
        std::cout << "[DEBUG] Getting MarkerInteractableData ChallengeValue: " << mChallengeValue << std::endl;
        return mChallengeValue;
    }

    // Marker
    void Marker::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] Marker::Read started." << std::endl;
        mName = utils::xml_get_text_node(node, "markerName");
        std::cout << "[DEBUG] markerName: " << mName << std::endl;
        mId = utils::xml_get_text_node<uint32_t>(node, "markerId");
        std::cout << "[DEBUG] markerId: " << mId << std::endl;
        mNounName = utils::xml_get_text_node(node, "nounDef");
        std::cout << "[DEBUG] nounDef: " << mNounName << std::endl;
        mNoun = utils::hash_id(mNounName);
        std::cout << "[DEBUG] noun (hashed): " << mNoun << std::endl;

        mPosition = read_vec3(node.child("pos"));
        mRotation = read_vec3(node.child("rotDegrees"));
        mScale = utils::xml_get_text_node<float>(node, "scale");
        std::cout << "[DEBUG] scale: " << mScale << std::endl;

        mVisible = utils::xml_get_text_node<bool>(node, "visible");
        std::cout << "[DEBUG] visible: " << (mVisible ? "true" : "false") << std::endl;
        mHasCollision = utils::xml_get_text_node<bool>(node, "createWithCollision");
        std::cout << "[DEBUG] createWithCollision: " << (mHasCollision ? "true" : "false") << std::endl;

        mOverrideAssetId = utils::xml_get_text_node<uint64_t>(node, "assetOverrideId");
        std::cout << "[DEBUG] assetOverrideId: " << mOverrideAssetId << std::endl;
        mTargetId = utils::xml_get_text_node<uint32_t>(node, "targetMarkerId");
        std::cout << "[DEBUG] targetMarkerId: " << mTargetId << std::endl;

        if (auto componentDataNode = node.child("componentData")) {
            std::cout << "[DEBUG] Found componentData node." << std::endl;
            if (auto teleporterNode = componentDataNode.child("teleporter")) {
                std::cout << "[DEBUG] Found teleporter node in componentData." << std::endl;
                mTeleporterData = std::make_unique<TeleporterData>();
                mTeleporterData->Read(teleporterNode);
            }
            if (auto interactableNode = componentDataNode.child("interactable")) {
                std::cout << "[DEBUG] Found interactable node in componentData." << std::endl;
                mInteractableData = std::make_unique<MarkerInteractableData>();
                mInteractableData->Read(interactableNode);
            }
            // Additional component data logging can be added here if necessary.
        }
        std::cout << "[DEBUG] Marker::Read finished." << std::endl;
    }

    const std::unique_ptr<TeleporterData>& Marker::GetTeleporterData() const {
        std::cout << "[DEBUG] Getting Marker TeleporterData." << std::endl;
        return mTeleporterData;
    }

    const std::unique_ptr<MarkerInteractableData>& Marker::GetInteractableData() const {
        std::cout << "[DEBUG] Getting Marker InteractableData." << std::endl;
        return mInteractableData;
    }

    const glm::vec3& Marker::GetPosition() const {
        std::cout << "[DEBUG] Getting Marker Position: (" 
                  << mPosition.x << ", " << mPosition.y << ", " << mPosition.z << ")" << std::endl;
        return mPosition;
    }

    const glm::vec3& Marker::GetRotation() const {
        std::cout << "[DEBUG] Getting Marker Rotation: (" 
                  << mRotation.x << ", " << mRotation.y << ", " << mRotation.z << ")" << std::endl;
        return mRotation;
    }

    const std::string& Marker::GetNounName() const {
        std::cout << "[DEBUG] Getting Marker NounName: " << mNounName << std::endl;
        return mNounName;
    }

    uint64_t Marker::GetOverrideAssetId() const {
        std::cout << "[DEBUG] Getting Marker OverrideAssetId: " << mOverrideAssetId << std::endl;
        return mOverrideAssetId;
    }

    uint32_t Marker::GetId() const {
        std::cout << "[DEBUG] Getting Marker Id: " << mId << std::endl;
        return mId;
    }

    uint32_t Marker::GetNoun() const {
        std::cout << "[DEBUG] Getting Marker Noun: " << mNoun << std::endl;
        return mNoun;
    }

    uint32_t Marker::GetTargetId() const {
        std::cout << "[DEBUG] Getting Marker TargetId: " << mTargetId << std::endl;
        return mTargetId;
    }

    float Marker::GetScale() const {
        std::cout << "[DEBUG] Getting Marker Scale: " << mScale << std::endl;
        return mScale;
    }

    // Markerset
    bool Markerset::Load(const std::string& path) {
        std::cout << "[DEBUG] Markerset::Load started for path: " << path << std::endl;
        const std::string fullPath = levelDataPath + path;
        if (!std::filesystem::exists(fullPath)) {
            std::cout << "[DEBUG] Markerset: Could not find '" << fullPath << "'." << std::endl;
            return false;
        }

        pugi::xml_document document;
        if (auto parse_result = document.load_file(fullPath.c_str())) {
            std::cout << "[DEBUG] Markerset XML file loaded: " << fullPath << std::endl;
            auto node = document.child("markerset");
            if (node) {
                Read(node);
                std::cout << "[DEBUG] Markerset::Load finished successfully." << std::endl;
                return true;
            }
        } else {
            std::cout << "[DEBUG] Markerset: Could not load '" << path << "'." << std::endl;
        }
        std::cout << "[DEBUG] Markerset::Load failed." << std::endl;
        return false;
    }

    void Markerset::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] Markerset::Read started." << std::endl;
        for (const auto& child : node.child("markers")) {
            if (!utils::string_iequals(child.name(), "entry")) {
                continue;
            }
            std::cout << "[DEBUG] Reading a Marker entry in Markerset." << std::endl;
            auto marker = std::make_shared<Marker>();
            marker->Read(child);
            mMarkersByNoun[marker->mNoun].push_back(marker);
            mMarkers.push_back(std::move(marker));
        }
        std::cout << "[DEBUG] Markerset::Read finished." << std::endl;
    }

    const std::vector<MarkerPtr>& Markerset::GetMarkers() const {
        std::cout << "[DEBUG] Getting all Markerset Markers." << std::endl;
        return mMarkers;
    }

    std::vector<MarkerPtr> Markerset::GetMarkersByType(uint32_t noun) const {
        std::cout << "[DEBUG] Getting Markerset Markers by type (noun): " << noun << std::endl;
        if (auto it = mMarkersByNoun.find(noun); it != mMarkersByNoun.end()) {
            return it->second;
        }
        std::cout << "[DEBUG] No Markerset Markers found for noun: " << noun << std::endl;
        return {};
    }

    // DirectorClass
    void DirectorClass::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] DirectorClass::Read started." << std::endl;
        mNounName = utils::xml_get_text_node(node, "mpNoun");
        std::cout << "[DEBUG] mpNoun: " << mNounName << std::endl;
        mMinLevel = utils::xml_get_text_node<int32_t>(node, "minDifficulty");
        std::cout << "[DEBUG] minDifficulty: " << mMinLevel << std::endl;
        mMaxLevel = utils::xml_get_text_node<int32_t>(node, "maxDifficulty");
        std::cout << "[DEBUG] maxDifficulty: " << mMaxLevel << std::endl;
        mHordeLegal = utils::xml_get_text_node<bool>(node, "hordeLegal");
        std::cout << "[DEBUG] hordeLegal: " << (mHordeLegal ? "true" : "false") << std::endl;
        std::cout << "[DEBUG] DirectorClass::Read finished." << std::endl;
    }

    const std::string& DirectorClass::GetNounName() const {
        std::cout << "[DEBUG] Getting DirectorClass NounName: " << mNounName << std::endl;
        return mNounName;
    }

    int32_t DirectorClass::GetMinLevel() const {
        std::cout << "[DEBUG] Getting DirectorClass MinLevel: " << mMinLevel << std::endl;
        return mMinLevel;
    }

    int32_t DirectorClass::GetMaxLevel() const {
        std::cout << "[DEBUG] Getting DirectorClass MaxLevel: " << mMaxLevel << std::endl;
        return mMaxLevel;
    }

    bool DirectorClass::IsHordeLegal() const {
        std::cout << "[DEBUG] Getting DirectorClass HordeLegal: " << (mHordeLegal ? "true" : "false") << std::endl;
        return mHordeLegal;
    }

    // LevelConfig
    void LevelConfig::Read(pugi::xml_node node) {
        std::cout << "[DEBUG] LevelConfig::Read started." << std::endl;
        read_list(node, "minion", mMinions);
        read_list(node, "special", mSpecial);
        read_list(node, "boss", mBoss);
        read_list(node, "agent", mAgent);
        read_list(node, "captain", mCaptain);
        std::cout << "[DEBUG] LevelConfig::Read finished." << std::endl;
    }

    DirectorClass LevelConfig::GetMinion(size_t idx) const {
        std::cout << "[DEBUG] Getting LevelConfig Minion at index: " << idx << std::endl;
        return mMinions.size() > idx ? mMinions[idx] : DirectorClass();
    }

    DirectorClass LevelConfig::GetSpecial(size_t idx) const {
        std::cout << "[DEBUG] Getting LevelConfig Special at index: " << idx << std::endl;
        return mSpecial.size() > idx ? mSpecial[idx] : DirectorClass();
    }

    DirectorClass LevelConfig::GetBoss(size_t idx) const {
        std::cout << "[DEBUG] Getting LevelConfig Boss at index: " << idx << std::endl;
        return mBoss.size() > idx ? mBoss[idx] : DirectorClass();
    }

    DirectorClass LevelConfig::GetAgent(size_t idx) const {
        std::cout << "[DEBUG] Getting LevelConfig Agent at index: " << idx << std::endl;
        return mAgent.size() > idx ? mAgent[idx] : DirectorClass();
    }

    DirectorClass LevelConfig::GetCaptain(size_t idx) const {
        std::cout << "[DEBUG] Getting LevelConfig Captain at index: " << idx << std::endl;
        return mCaptain.size() > idx ? mCaptain[idx] : DirectorClass();
    }

    // Level
    Level::Level() {
        std::cout << "[DEBUG] Level constructor called." << std::endl;
    }

    Level::~Level() {
        std::cout << "[DEBUG] Level destructor called." << std::endl;
    }

    bool Level::Load(const std::string& difficultyName, const std::string& levelName) {
        std::cout << "[DEBUG] Level::Load started for difficulty: " << difficultyName << ", level: " << levelName << std::endl;
        const std::string fullPath = levelDataPath + difficultyName + "/" + levelName + ".level.xml";
        if (!std::filesystem::exists(fullPath)) {
            std::cout << "[DEBUG] Level: Could not find '" << fullPath << "'." << std::endl;
            return false;
        }

        pugi::xml_document document;
        if (auto parse_result = document.load_file(fullPath.c_str())) {
            std::cout << "[DEBUG] Level XML file loaded: " << fullPath << std::endl;
            auto node = document.child("level");
            if (!node) {
                std::cout << "[DEBUG] No 'level' node found in XML." << std::endl;
                return false;
            }

            for (const auto& child : node.child("markersets")) {
                if (!utils::string_iequals(child.name(), "entry")) {
                    continue;
                }

                const auto markersetAsset = utils::xml_get_text_node(child, "markersetAsset");
                std::cout << "[DEBUG] Found markersetAsset: " << markersetAsset << std::endl;
                if (markersetAsset.empty()) {
                    std::cout << "[DEBUG] markersetAsset is empty, skipping entry." << std::endl;
                    continue;
                }

                const auto& [it, added] = mMarkersets.try_emplace(utils::hash_id(markersetAsset));
                if (added) {
                    it->second.mName = markersetAsset;
                    std::string markersetPath = difficultyName + "/" + markersetAsset + ".xml";
                    std::cout << "[DEBUG] Loading Markerset from: " << markersetPath << std::endl;
                    it->second.Load(markersetPath);
                }
            }

            mConfig.Read(node.child("levelConfig"));
            mFirstTimeConfig.Read(node.child("firstTimeConfig"));

            const auto planetConfigName = utils::xml_get_text_node(node, "planetConfig");
            if (!planetConfigName.empty()) {
                std::cout << "[DEBUG] Found planetConfig: " << planetConfigName << ". (Not processed)" << std::endl;
                // mPlanetConfig.Read(open_the_file);
            }

            std::cout << "[DEBUG] Level::Load finished successfully." << std::endl;
            return true;
        } else {
            std::cout << "[DEBUG] Level: Could not load '" << fullPath << "'." << std::endl;
        }
        std::cout << "[DEBUG] Level::Load failed." << std::endl;
        return false;
    }

    bool Level::GetMarkerset(const std::string& name, Markerset& markerset) const {
        std::cout << "[DEBUG] Level::GetMarkerset called for name: " << name << std::endl;
        if (auto it = mMarkersets.find(utils::hash_id(name)); it != mMarkersets.end()) {
            markerset = it->second;
            std::cout << "[DEBUG] Markerset found for name: " << name << std::endl;
            return true;
        }
        std::cout << "[DEBUG] No markerset found for name: " << name << std::endl;
        return false;
    }

    const LevelConfig& Level::GetConfig() const {
        std::cout << "[DEBUG] Getting Level Config." << std::endl;
        return mConfig;
    }

    const LevelConfig& Level::GetFirstTimeConfig() const {
        std::cout << "[DEBUG] Getting Level FirstTimeConfig." << std::endl;
        return mFirstTimeConfig;
    }

    const LevelConfig& Level::GetPlanetConfig() const {
        std::cout << "[DEBUG] Getting Level PlanetConfig." << std::endl;
        return mPlanetConfig;
    }
}
