name: Build (Windows x64)

on:
  push:
    branches:
      - master
      - merge/dalkon_2
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Instalar OpenSSL
        run: |
          choco install openssl.light -y

      - name: Definir variáveis de ambiente do OpenSSL
        run: |
          $env:OPENSSL_ROOT_DIR = 'C:\Program Files\OpenSSL-Win64'
          $env:OPENSSL_INCLUDE_DIR = 'C:\Program Files\OpenSSL-Win64\include'
          $env:OPENSSL_LIB_DIR = 'C:\Program Files\OpenSSL-Win64\lib'

      - name: Instalar Dependências Necessárias
        run: |
          choco install python --version=3.9.0 -y

      - name: Instalar Strawberry Perl
        run: choco install strawberryperl -y

      - name: Baixar e Extrair Boost
        run: |
          # Definir a versão do Boost
          $boostVersion = '1.81.0'
          $boostVersionUnderscore = $boostVersion -replace '\.', '_'

          # Definir a URL para o arquivo zip do Boost
          $boostUrl = "https://boostorg.jfrog.io/artifactory/main/release/$boostVersion/source/boost_$boostVersionUnderscore.zip"

          # Criar o diretório 'libs' se não existir
          if (!(Test-Path -Path "$env:GITHUB_WORKSPACE\darkspore_server\libs")) {
            New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\darkspore_server\libs"
          }

          # Baixar o Boost
          Invoke-WebRequest -Uri $boostUrl -OutFile boost.zip

          # Extrair o Boost para o diretório 'libs'
          Expand-Archive -Path boost.zip -DestinationPath "$env:GITHUB_WORKSPACE\darkspore_server\libs"

          # Remover o arquivo zip para economizar espaço
          Remove-Item boost.zip

      - name: Construir Bibliotecas Boost
        working-directory: ${{ github.workspace }}\darkspore_server\libs\boost_1_81_0
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          bootstrap.bat
          if %ERRORLEVEL% neq 0 (
            type bootstrap.log
            exit /b %ERRORLEVEL%
          )
          .\b2.exe -d2 --with-system --with-thread variant=release link=shared threading=multi runtime-link=shared address-model=64

      - name: Exibir bootstrap.log em caso de falha
        if: failure()
        working-directory: ${{ github.workspace }}\darkspore_server\libs\boost_1_81_0
        run: type bootstrap.log

      - name: Instalar MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Executar MSBuild
        working-directory: ${{ github.workspace }}\darkspore_server
        run: msbuild .\darkspore_server.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: recap-server-windows-x64
          path: ${{ github.workspace }}\darkspore_server\build
