name: Build (Windows x64)

on:
  push:
    branches:
      - master
      - merge/dalkon_2
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Download and unzip Boost 1.73.0
        run: |
          curl -L -o boost_1_73_0.zip https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.zip
          7z x boost_1_73_0.zip
        shell: cmd

      - name: Bootstrap Boost
        run: |
          cd boost_1_73_0
          bootstrap.bat
        shell: cmd
        
      - name: Build Boost
        run: |
          cd boost_1_73_0
          .\b2 --with-filesystem --with-system --with-thread --with-date_time --with-regex --with-serialization --with-chrono --with-atomic --with-log --toolset=msvc-14.2 address-model=64 link=static runtime-link=shared stage
        shell: cmd
        
      - name: Show bootstrap log
        run: cat boost_1_73_0/bootstrap.log
        shell: bash

      - name: Set environment variables for Boost
        run: |
          echo BOOST_ROOT=${{ runner.workspace }}\boost_1_73_0 >> $GITHUB_ENV
          echo BOOST_LIBRARYDIR=${{ runner.workspace }}\boost_1_73_0\stage\lib >> $GITHUB_ENV
          echo INCLUDE_PATH=${{ runner.workspace }}\recap_server\darkspore_server\source;${{ runner.workspace }}\recap_server\darkspore_server\libs\boost_1_73_0\include;${{ runner.workspace }}\recap_server\darkspore_server\libs\rapidjson-1.1.0\include >> $GITHUB_ENV
          echo LIBRARY_PATH=${{ runner.workspace }}\recap_server\darkspore_server\libs\boost_1_73_0\lib >> $GITHUB_ENV

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Debug Environment Variables
        run: |
          echo "INCLUDE_PATH=${{ env.INCLUDE_PATH }}"
          echo "LIBRARY_PATH=${{ env.LIBRARY_PATH }}"

      - name: Run MSBuild
        working-directory: ${{ github.workspace }}
        run: |
          msbuild .\darkspore_server.sln /p:Configuration=Release /p:Platform=x64 /p:IncludePath="${{ env.INCLUDE_PATH }}" /p:LibraryPath="${{ env.LIBRARY_PATH }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: recap-server-windows-x64
          path: ${{ runner.workspace }}\recap_server\darkspore_server\build
