name: Build ReCap Server (Ubuntu)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install g++-13 cmake libfindbin-libs-perl libstdc++-13-dev build-essential git
          sudo apt-get -y install libfuse2

      - name: Set LDFLAGS environment
        run: echo "LDFLAGS=-Wl,--copy-dt-needed-entries" >> $GITHUB_ENV

      - name: Configure
        run: |
          cd darkspore_server
          cmake . -B build -DCMAKE_INSTALL_PREFIX=./AppDir/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-narrowing"

      - name: Build
        run: |
          cd darkspore_server
          cmake --build build
          cmake -DCOMPONENT=recap_server -Pbuild/cmake_install.cmake

      - uses: actions/upload-artifact@v4
        with:
          name: recap-server-ubuntu-x64
          path: |
            darkspore_server/AppDir/usr/lib/
            darkspore_server/AppDir/usr/bin/

      - name: Fetch AppImage tools
        run: |
          cd darkspore_server
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod a+x linuxdeploy-*.AppImage

      - name: Build the AppImage
        run: |
          cd darkspore_server
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/AppDir/usr/lib
          ./linuxdeploy-x86_64.AppImage --list-plugins
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
          rm ./linuxdeploy-x86_64.AppImage

      - name: Preparing artifacts (appimage-x86_64)
        run: |
          cd darkspore_server
          mkdir dist_appimage
          mv *.AppImage ./dist_appimage/

      - name: Adding needed files
        run: |
          cd darkspore_server
          cp -r res/data dist_appimage/data
          mkdir -p dist_appimage/storage/user
          touch dist_appimage/storage/user/PLACEHOLDER

      - uses: actions/upload-artifact@v4
        with:
          name: recap-server-appimage-x86_64
          path: darkspore_server/dist_appimage
