name: Build ReCap Server

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install g++-13 cmake libfindbin-libs-perl libstdc++-13-dev build-essential git
          sudo apt-get -y install libfuse2

      - name: Set LDFLAGS environment
        run: echo "LDFLAGS=-Wl,--copy-dt-needed-entries" >> $GITHUB_ENV

      - name: Configure
        run: |
          cd darkspore_server
          cmake . -B build -DCMAKE_INSTALL_PREFIX=./AppDir/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-narrowing"

      - name: Build
        run: |
          cd darkspore_server
          cmake --build build
          cmake -DCOMPONENT=recap_server -Pbuild/cmake_install.cmake

      - name: Upload Ubuntu binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recap-server-ubuntu-x64
          path: |
            darkspore_server/AppDir/usr/lib/
            darkspore_server/AppDir/usr/bin/

      - name: Fetch AppImage tools
        run: |
          cd darkspore_server
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod a+x linuxdeploy-*.AppImage

      - name: Build the AppImage
        run: |
          cd darkspore_server
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/AppDir/usr/lib
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
          rm ./linuxdeploy-x86_64.AppImage

      - name: Prepare AppImage artifacts
        run: |
          cd darkspore_server
          mkdir dist_appimage
          mv *.AppImage ./dist_appimage/
          cp -r res/data dist_appimage/data
          mkdir -p dist_appimage/storage/user
          touch dist_appimage/storage/user/PLACEHOLDER

      - name: Upload AppImage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recap-server-appimage-x86_64
          path: darkspore_server/dist_appimage

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          pacboy: gcc:p cmake:p make:p

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.30'

      - name: Set up NASM
        uses: ilammy/setup-nasm@v1

      - name: Set up Git
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm git

      - name: Configure
        run: |
          cd darkspore_server
          export PATH=/c/Users/runneradmin/nasm:$PATH
          cmake . -B build -G "Visual Studio 17 2022" -DCMAKE_PREFIX_PATH="C:\\hostedtoolcache\\windows\\perl\\5.30.3-thr\\x64\\bin" -DCMAKE_INSTALL_PREFIX=./dist

      - name: Build
        run: |
          cd darkspore_server/build
          export PATH=/c/Users/runneradmin/nasm:$PATH
          cmake --build . --config Release
          cmake -DCOMPONENT=recap_server -Pcmake_install.cmake

      - name: Prepare Windows artifacts
        run: |
          cd darkspore_server
          cp -r res/data dist/bin/data
          mkdir -p dist/bin/storage/user
          touch dist/bin/storage/user/PLACEHOLDER

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recap-server-windows-x64
          path: ${{runner.workspace}}/recap_server/darkspore_server/dist

