name: Build (Windows x64)

on:
  push:
    branches:
      - master
      - merge/dalkon_2
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Instalar OpenSSL
        run: |
          choco install openssl.light -y

      - name: Definir variáveis de ambiente do OpenSSL
        run: |
          $env:OPENSSL_ROOT_DIR = 'C:\Program Files\OpenSSL-Win64'
          $env:OPENSSL_INCLUDE_DIR = 'C:\Program Files\OpenSSL-Win64\include'
          $env:OPENSSL_LIB_DIR = 'C:\Program Files\OpenSSL-Win64\lib'

      - name: Instalar Strawberry Perl
        run: choco install strawberryperl -y

      - name: Construir Bibliotecas Boost
        working-directory: ${{ github.workspace }}\recap_server\darkspore_server\libs\boost_1_73_0
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          bootstrap.bat
          if %ERRORLEVEL% neq 0 (
            type bootstrap.log
            exit /b %ERRORLEVEL%
          )
          .\b2.exe --with-system --with-thread variant=release link=shared threading=multi runtime-link=shared address-model=64

      - name: Instalar MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Executar MSBuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\darkspore_server.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: recap-server-windows-x64
          path: ${{ github.workspace }}\recap_server\darkspore_server\build
