name: Build ReCap (Linux)

on:
  push:
    branches:
      - master
      - feature/cmake
      - original/cmake
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install g++-13 cmake libfindbin-libs-perl libstdc++-13-dev build-essential git
          sudo apt-get -y install libfuse2

      - name: Set LDFLAGS environment
        run: echo "LDFLAGS=-Wl,--copy-dt-needed-entries" >> $GITHUB_ENV

      - name: Configure
        run: |
          cd darkspore_server
          cmake . -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -Wno-narrowing"

      - name: Build
        run: |
          cd darkspore_server
          cmake --build build
          DESTDIR=AppDir cmake --install build

      - uses: actions/upload-artifact@v4
        with:
          name: recap-server-linux-x64
          path: darkspore_server/AppDir/usr/bin/

      - name: Fetch AppImage tools
        run: |
          cd darkspore_server
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod a+x linuxdeploy-*.AppImage

      - name: Build the AppImage
        run: |
          cd darkspore_server
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(find $(pwd)/build/_deps -maxdepth 1 -mindepth 1 -type d | tr '\n' ':')
          ./linuxdeploy-x86_64.AppImage --list-plugins
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage

      - name: Preparing artifacts (appimage-x86_64)
        run: |
          cd darkspore_server
          mkdir dist_appimage
          mv *.AppImage ./dist_appimage/

      - uses: actions/upload-artifact@v4
        with:
          name: recap-server-appimage-x86_64
          path: darkspore_server/dist_appimage
